x = open("/Users/noahfedosoff_S/Documents/Projects/tale.txt", "r")
g = x.read().upper()
c = open("upper.txt")
f = open("/Users/noahfedosoff_S/Documents/Projects/upper.txt", "w+")
f.write(g)
a = open("/Users/noahfedosoff_S/Documents/Projects/upper.txt", "a")
print(a.write("ok new"))
v = open("upper.txt","x")

f.close()
x.close()
c.close()
a.close()
v.close()
