print("script starting")
f = open("/Users/noahfedosoff_S/Documents/Projects/Unit4/sampletext.txt", "r")
print(f.read())
f.close()
g = open(r"/Users/noahfedosoff_S/Documents/Projects/Unit4/sampletext.txt", "w+")
g.write("ok new".upper())
print(g.read())
g.close()
open("newsampletext.txt", "w+")
x = open("/Users/noahfedosoff_S/Documents/Projects/newsampletext.txt", "w")
x.write("ok new".upper())
x.close()
b = open("/Users/noahfedosoff_S/Documents/Projects/newsampletext.txt", "r")
print(b.read())
print("script ending")
